"""Assortment of BiDAF layers for use in models.py.

Author:
    Xiao Lu (shawlu@stanford.edu)
    Chris Chute (chute@stanford.edu)
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence
from util import masked_softmax

class SyllEmbedding(nn.Module):
    def __init__(self, syll_vectors, e_syll, e_word, drop_prob=0, freeze=False):
        super(SyllEmbedding, self).__init__()

        self.e_syll = e_syll
        self.e_word = e_word
        self.drop_prob = drop_prob

        self.embeddings = nn.Embedding.from_pretrained(syll_vectors, freeze=freeze) 
        
        self.encoder = nn.LSTM(input_size=e_syll, 
                               bidirectional=True, 
                               hidden_size=int(e_word / 2),
                               batch_first=True)

    def forward(self, input):
        """
        @param input (Tensor): indices of character batch (batch_size, sentence_length, max_word_length)
        @returns last_hidden (Tensor): Tensor of shape (batch_size, sentence_length, 2 * e_word)
        """
        x_emb = self.embeddings(input)
        batch_size, sentence_length, max_word_length, e_syll = x_emb.shape
        
        # reshape to (batch_size * sentence_length, max_word_length, e_syll)
        x_emb = x_emb.reshape(batch_size * sentence_length, max_word_length, e_syll)
        
        # last_hidden: (2, batch_size * sentence_length, e_word / 2)
        _, (last_hidden, _) = self.encoder(x_emb)
        
        # concate the two direction hidden states into shape (batch_size * sentence_length, e_word)
        last_hidden = torch.cat([last_hidden[0], last_hidden[1]], dim=1)
        
        # break apart dimension to (batch_size, sentence_length, e_word)
        emb = last_hidden.reshape(batch_size, sentence_length, -1)

        return emb

class CharEmbedding(nn.Module):
    def __init__(self, char_vectors, e_char, e_word, drop_prob, freeze=True):
        """
        The character-level embeddings are generated by taking the 
        final hidden states of a bi-directional recurrent neural 
        network (RNN) applied to embeddings of characters in the token.
        """
        super(CharEmbedding, self).__init__()
        
        self.e_char = e_char
        self.e_word = e_word
        self.drop_prob = drop_prob

        self.embeddings = nn.Embedding.from_pretrained(char_vectors, freeze=freeze) 
        
        self.encoder = nn.LSTM(input_size=e_char, 
                               bidirectional=True, 
                               hidden_size=int(e_word / 2),
                               batch_first=True)

    def forward(self, input):
        """
        @param input (Tensor): indices of character batch (batch_size, sentence_length, max_word_length)
        @returns last_hidden (Tensor): Tensor of shape (batch_size, sentence_length, e_word)
        """
        x_emb = self.embeddings(input)
        batch_size, sentence_length, max_word_length, e_char = x_emb.shape
        
        # reshape to (batch_size * sentence_length, max_word_length, e_char)
        x_emb = x_emb.reshape(batch_size * sentence_length, max_word_length, e_char)
        
        # last_hidden: (2, batch_size * sentence_length, e_word / 2)
        _, (last_hidden, _) = self.encoder(x_emb)
        
        # concate the two direction hidden states into shape (batch_size * sentence_length, e_word)
        last_hidden = torch.cat([last_hidden[0], last_hidden[1]], dim=1)
        
        # break apart dimension to (batch_size, sentence_length, e_word)
        last_hidden = last_hidden.reshape(batch_size, sentence_length, -1)
        last_hidden = F.dropout(last_hidden, self.drop_prob, self.training)
        return last_hidden

class WordEmbedding(nn.Module):
    """Embedding layer used by BiDAF, WITHOUT the character-level component.

    Word-level embeddings are further refined using a 2-layer Highway Encoder
    (see `HighwayEncoder` class for details).

    Args:
        word_vectors (torch.Tensor): Pre-trained word vectors.
        hidden_size (int): Size of hidden activations (default 100)
        drop_prob (float): Probability of zero-ing out activations
    """
    def __init__(self, word_vectors, hidden_size, drop_prob):
        super(WordEmbedding, self).__init__()
        # self.drop_prob = drop_prob
        self.embed = nn.Embedding.from_pretrained(word_vectors) # (88714, 300)
        # self.proj = nn.Linear(word_vectors.size(1), hidden_size, bias=False) # in 300, out 100
        # self.hwy = HighwayEncoder(2, hidden_size)

    def forward(self, x):
        emb = self.embed(x)   # (batch_size, seq_len, embed_size)
        # emb = self.proj(emb)  # (batch_size, seq_len, hidden_size)
        # emb = self.hwy(emb)   # (batch_size, seq_len, hidden_size)
        # emb = F.dropout(emb, self.drop_prob, self.training)

        return emb


class HighwayEncoder(nn.Module):
    """Encode an input sequence using a highway network.

    Based on the paper:
    "Highway Networks"
    by Rupesh Kumar Srivastava, Klaus Greff, Jürgen Schmidhuber
    (https://arxiv.org/abs/1505.00387).

    Args:
        num_layers (int): Number of layers in the highway encoder.
        hidden_size (int): Size of hidden activations.
    """
    def __init__(self, num_layers, hidden_size):
        super(HighwayEncoder, self).__init__()
        self.transforms = nn.ModuleList([nn.Linear(hidden_size, hidden_size)
                                         for _ in range(num_layers)])
        self.gates = nn.ModuleList([nn.Linear(hidden_size, hidden_size)
                                    for _ in range(num_layers)])

    def forward(self, x):
        for gate, transform in zip(self.gates, self.transforms):
            # Shapes of g, t, and x are all (batch_size, seq_len, hidden_size)
            g = torch.sigmoid(gate(x))
            t = F.relu(transform(x))
            x = g * t + (1 - g) * x

        return x


class RNNEncoder(nn.Module):
    """General-purpose layer for encoding a sequence using a bidirectional RNN.

    Encoded output is the RNN's hidden state at each position, which
    has shape `(batch_size, seq_len, hidden_size * 2)`.

    Args:
        input_size (int): Size of a single timestep in the input.
        hidden_size (int): Size of the RNN hidden state.
        num_layers (int): Number of layers of RNN cells to use.
        drop_prob (float): Probability of zero-ing out activations.
    """
    def __init__(self,
                 input_size, # 100
                 hidden_size, # 100
                 num_layers, # 1
                 drop_prob=0.): # 0.2
        super(RNNEncoder, self).__init__()
        self.drop_prob = drop_prob
        self.rnn = nn.LSTM(input_size, hidden_size, num_layers,
                           batch_first=True,
                           bidirectional=True,
                           dropout=drop_prob if num_layers > 1 else 0.)

    def forward(self, x, lengths):
        # Save original padded length for use by pad_packed_sequence
        orig_len = x.size(1)

        # Sort by length and pack sequence for RNN
        lengths, sort_idx = lengths.sort(0, descending=True)
        x = x[sort_idx]     # (batch_size, seq_len, input_size)
        x = pack_padded_sequence(x, lengths, batch_first=True)

        # Apply RNN (h_i is of dimension 2H, forward and backward hidden states are concatenated
        x, _ = self.rnn(x)  # (batch_size, seq_len, 2 * hidden_size)

        # Unpack and reverse sort
        x, _ = pad_packed_sequence(x, batch_first=True, total_length=orig_len)
        _, unsort_idx = sort_idx.sort(0)
        x = x[unsort_idx]   # (batch_size, seq_len, 2 * hidden_size)

        # Apply dropout (RNN applies dropout after all but the last layer)
        x = F.dropout(x, self.drop_prob, self.training)

        return x


class BiDAFAttention(nn.Module):
    """Bidirectional attention originally used by BiDAF.

    Bidirectional attention computes attention in two directions:
    The context attends to the query and the query attends to the context.
    The output of this layer is the concatenation of [context, c2q_attention,
    context * c2q_attention, context * q2c_attention]. This concatenation allows
    the attention vector at each timestep, along with the embeddings from
    previous layers, to flow through the attention layer to the modeling layer.
    The output has shape (batch_size, context_len, 8 * hidden_size).

    Args:
        hidden_size (int): Size of hidden activations.
        drop_prob (float): Probability of zero-ing out activations.
    """
    def __init__(self, hidden_size, drop_prob=0.1):
        super(BiDAFAttention, self).__init__()
        self.drop_prob = drop_prob # 0.2
        self.c_weight = nn.Parameter(torch.zeros(hidden_size, 1)) # (200, 1)
        self.q_weight = nn.Parameter(torch.zeros(hidden_size, 1)) # (200, 1)
        self.cq_weight = nn.Parameter(torch.zeros(1, 1, hidden_size))
        for weight in (self.c_weight, self.q_weight, self.cq_weight):
            nn.init.xavier_uniform_(weight)
        self.bias = nn.Parameter(torch.zeros(1))

    def forward(self, c, q, c_mask, q_mask): # context N words, question M words
        batch_size, c_len, _ = c.size()
        q_len = q.size(1)
        s = self.get_similarity_matrix(c, q)        # (batch_size, c_len, q_len)
        c_mask = c_mask.view(batch_size, c_len, 1)  # (batch_size, c_len, 1)
        q_mask = q_mask.view(batch_size, 1, q_len)  # (batch_size, 1, q_len)
        s1 = masked_softmax(s, q_mask, dim=2)       # (batch_size, c_len, q_len)
        s2 = masked_softmax(s, c_mask, dim=1)       # (batch_size, c_len, q_len)

        # (bs, c_len, q_len) x (bs, q_len, 200 hid_size) => (bs, c_len, 200 hid_size)
        a = torch.bmm(s1, q) # C2Q attention

        # (bs, c_len, c_len) x (bs, c_len, 200 hid_size) => (bs, c_len, 200 hid_size)
        b = torch.bmm(torch.bmm(s1, s2.transpose(1, 2)), c) # Q2C attention, where is max?

        x = torch.cat([c, a, c * a, c * b], dim=2)  # (bs, c_len, 4 * 200 hid_size)

        return x

    def get_similarity_matrix(self, c, q):
        """Get the "similarity matrix" between context and query (using the
        terminology of the BiDAF paper).

        A naive implementation as described in BiDAF would concatenate the
        three vectors then project the result with a single weight matrix. This
        method is a more memory-efficient implementation of the same operation.

        See Also:
            Equation 1 in https://arxiv.org/abs/1611.01603
        """
        c_len, q_len = c.size(1), q.size(1)
        c = F.dropout(c, self.drop_prob, self.training)  # (bs, c_len, hid_size)
        q = F.dropout(q, self.drop_prob, self.training)  # (bs, q_len, hid_size)

        # Shapes: (batch_size, c_len, q_len)
        s0 = torch.matmul(c, self.c_weight).expand([-1, -1, q_len])
        s1 = torch.matmul(q, self.q_weight).transpose(1, 2)\
                                           .expand([-1, c_len, -1])
        s2 = torch.matmul(c * self.cq_weight, q.transpose(1, 2))
        s = s0 + s1 + s2 + self.bias

        return s


class BiDAFOutput(nn.Module):
    """Output layer used by BiDAF for question answering.

    Computes a linear transformation of the attention and modeling
    outputs, then takes the softmax of the result to get the start pointer.
    A bidirectional LSTM is then applied the modeling output to produce `mod_2`.
    A second linear+softmax of the attention output and `mod_2` is used
    to get the end pointer.

    Args:
        hidden_size (int): Hidden size used in the BiDAF model.
        drop_prob (float): Probability of zero-ing out activations.
    """
    def __init__(self, hidden_size, drop_prob):
        super(BiDAFOutput, self).__init__()
        self.att_linear_1 = nn.Linear(8 * hidden_size, 1)
        self.mod_linear_1 = nn.Linear(2 * hidden_size, 1)

        self.rnn = RNNEncoder(input_size=2 * hidden_size,
                              hidden_size=hidden_size,
                              num_layers=1,
                              drop_prob=drop_prob)

        self.att_linear_2 = nn.Linear(8 * hidden_size, 1)
        self.mod_linear_2 = nn.Linear(2 * hidden_size, 1)

    def forward(self, att, mod, mask):
        """
        :param att: output from attention layer, # (bs, c_len, 8H)
        :param mod: output from modeling ayer, (bs, c_len, 2H)
        :param mask: binary mask of context paragraph, shape (bs, c_len)
        :return:
        """
        # Shapes: (batch_size, c_len, 1)
        logits_1 = self.att_linear_1(att) + self.mod_linear_1(mod)

        # (bs, c_len, 2H), 2 directions are concatenated
        mod_2 = self.rnn(mod, mask.sum(-1))

        logits_2 = self.att_linear_2(att) + self.mod_linear_2(mod_2)

        # Shapes: (batch_size, c_len)
        log_p1 = masked_softmax(logits_1.squeeze(), mask, log_softmax=True)
        log_p2 = masked_softmax(logits_2.squeeze(), mask, log_softmax=True)

        return log_p1, log_p2
